OPENAI_API_KEY="..."
ELEVEN_LABS_VOICE_ID="..."
ELEVEN_LABS_API_KEY="..."
WOLFRAM_API_KEY="..."

TWILIO_ACCOUNT_SID = "..."
TWILIO_AUTH_TOKEN = "..."
TWILIO_PHONE_NUMBER = "..."
RECIPIENT_PHONE_NUMBER = "..."

GOOGLE_API_KEY= "..."
GOOGLE_CSE_ID= "..."

SERVICE_ACCOUNT_FILE="..."
SCOPES="..."
GOOGLE_CALENDAR_ID="..."
GOOGLE_DOCS_ID="..."

AZURE_ENDPOINT="..."
AZURE_API_KEY="..."

PINECONE_API_KEY="..."
PINECONE_NAMESPACE="..."
PINECONE_ENVIRONMENT="..."

MAX_CONTEXT_SIZE=4000
MAX_MEMORY_ITEM_SIZE=2000
SUMMARIZER_CHUNK_SIZE=3000
CLEAR_DB_ON_START="true"
DEBUG="true"
MODEL="gpt-3.5-turbo"
SUMMARIZER_MODEL="gpt-3.5-turbo"
MEMORY_TYPE="pinecone" 
