OPENAI_API_KEY="..."
ELEVEN_LABS_VOICE_ID="..."
ELEVEN_LABS_API_KEY="..."
WOLFRAM_API_KEY="..."

TWILIO_ACCOUNT_SID = "..."
TWILIO_AUTH_TOKEN = "..."
TWILIO_PHONE_NUMBER = "..."
RECIPIENT_PHONE_NUMBER = "..."

GOOGLE_API_KEY= "..."
GOOGLE_CSE_ID= "..."

SERVICE_ACCOUNT_FILE="..."
SCOPES="..."
GOOGLE_CALENDAR_ID="..."